version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  api:
    build: ./docker/api
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  web:
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

networks: 
    default:
        name: sample-spa